spring.application.name=proyecto_1
spring.datasource.url=jdbc:mysql://mysql-3ad0f86-practica-2.h.aivencloud.com:16696/proyecto?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_7y97vG9KINBPkMPUxEB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# CONFIGURACION DE GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=examenii.pajr.4cm1@gmail.com
spring.mail.password=qxkm mwhi zcog vjbj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true